---
title: "Final Project"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---


```{r}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(dplyr)
library(readxl)
library(shiny)
library(shinyWidgets)
library(DT)
```

# Enrollment Data

```{r}
# Command + Option + I OR CTRL + ALT + I
er <- read_excel("er2025_2.xlsx")
cr <- read_excel("cr2025_2.xlsx")

cleaned_er <- er %>%
  group_by(across(-c(Specialization, `Specialization Desc`, Minor, `Minor Desc`))) %>%
  summarise(
    Specialization = paste(unique(Specialization), collapse = ", "),
    `Specialization Desc` = paste(unique(`Specialization Desc`), collapse = ", "),
    Minor = paste(unique(Minor), collapse = ", "),
    `Minor Desc`= paste(unique(`Minor Desc`), collapse = ", "), 
    .groups = "drop"
  ) %>% 
  ungroup()

cleaned_specialization <- cleaned_er %>%
  separate(
    col = Specialization,
    into = c("Specialization_1", "Specialization_2"),
    sep = ", ",
    remove = TRUE
  ) %>%
  select(`Student ID`, Specialization_1, Specialization_2)


spec_1 <- cleaned_specialization %>%
  select(`Student ID`, Specialization = Specialization_1)

spec_2 <- cleaned_specialization %>%
  select(`Student ID`, Specialization = Specialization_2)


combined <- bind_rows(spec_1, spec_2) %>%
  filter(Specialization != "NA") %>% # Removing the NA's
  mutate(Specialization = as.character(Specialization)) %>% # Making 'Specialization' a character
  distinct(`Student ID`, Specialization) %>%
  group_by(Specialization) %>%
  summarise(tot_students = n(), .groups = "drop") %>% 
  ungroup() 


plot <- reactive({
  
  combined %>% 
    filter(Specialization %in% input$picker_specialization) %>% 
    group_by(Specialization) %>% 
    summarise(
        tot_students = tot_students
    ) %>% 
    ungroup()
  
})


cleaned_minor <- cleaned_er %>%
  separate(
    col = Minor,
    into = c("Minor_1", "Minor_2"),
    sep = ", ",
    remove = TRUE
  ) %>%
  select(`Student ID`, Minor_1, Minor_2)


min_1 <- cleaned_minor %>%
  select(`Student ID`, Minor = Minor_1)

min_2 <- cleaned_minor %>%
  select(`Student ID`, Minor = Minor_2)


combined_minor <- bind_rows(min_1, min_2) %>%
  filter(Minor != "NA") %>% # Removing the NA's
  mutate(Minor = as.character(Minor)) %>% # Making 'Specialization' a character
  distinct(`Student ID`, Minor) %>%
  group_by(Minor) %>%
  summarise(tot_students = n(), .groups = "drop") %>% 
  ungroup() 



plot2 <- reactive({
  
  combined_minor %>%
    group_by(Minor) %>% 
    summarise(
      tot_students = tot_students
    ) %>% 
    ungroup()
  
})

joined_data <- inner_join(cleaned_er, cr, by = c("Student ID" = "SCS_Student"))



```



Column {.sidebar}
-----------------------------------------------------------------------

```{r}
shinyWidgets::pickerInput(
    inputId  = "picker_class",
    label    = h4("Class"),
    choices  = unique(cleaned_er$Class),
    selected = unique(cleaned_er$Class),
    multiple = TRUE,
    options  = list(
        `actions-box` = TRUE,
        size = 5,
        `selected-text-format` = "count > 2"
    )
)

shinyWidgets::pickerInput(
    inputId  = "picker_program",
    label    = h4("Program"),
    choices  = unique(cleaned_er$Program),
    selected = unique(cleaned_er$Program),
    multiple = TRUE,
    options  = list(
        `actions-box` = TRUE,
        size = 10,
        `selected-text-format` = "count > 2"
    )
)

shinyWidgets::pickerInput(
    inputId  = "picker_specialization",
    label    = h4("Specialization"),
    choices  = unique(combined$Specialization),
    selected = unique(combined$Specialization),
    multiple = TRUE,
    options  = list(
        `actions-box` = TRUE,
        size = 15,
        `selected-text-format` = "count > 2"
    )
)

br()
hr()
br()

actionButton(inputId = "reset", label = "Reset", icon = icon("sync"))

observeEvent(eventExpr = input$reset, handlerExpr = {
    
    updatePickerInput(
        session = session,
        inputId = "picker_class",
        selected = unique(cleaned_er$Class))
  
      updatePickerInput(
        session = session,
        inputId = "picker_program",
        selected = unique(cleaned_er$Program))
    
    updatePickerInput(
        session = session,
        inputId = "picker_specialization",
        selected = unique(combined$Specialization))
    
        
})

```



Row {data-width=650}
-----------------------------------------------------------------------
```{r}
summary <- reactive({
  
  cleaned_er %>%
    filter(Class %in% input$picker_class) %>% 
    filter(Program %in% input$picker_program) %>% 
    
    summarise(
      
      students_program = n_distinct(`Student ID`),
      avg_gpa = mean(GPA, na.rm = TRUE)
      
    ) %>% 
      
    mutate(
      
      avg_gpa = scales::number(avg_gpa, 0.01)
      
    )
})
```


```{r}
summary2 <- reactive({
  
  combined %>% 
    filter(Specialization %in% input$picker_specialization) %>% 
    
    summarise(
      
      students_specialization = sum(tot_students)
      
    ) 
  
})
```


### A
```{r}
renderValueBox({
  
  valueBox(
    value = summary()$students_program,
    caption = "Students by Program",
    color = "lightblue"
  )
  
})
```

### B
```{r}
renderValueBox({
  
  valueBox(
    value = summary2()$students_specialization,
    caption = "Students by Specialization",
    color = "lightgreen"
  )
  
})
```

### C
```{r}
renderValueBox({
  
  valueBox(
    value = summary()$avg_gpa,
    caption = "Average GPA",
    color = "tan"
  )
  
})
```



Row {.tabset}
-----------------------------------------------------------------------
### Breakdown by Specialization
```{r}
renderPlotly({
  
  plot_ly(
    data = plot(),
    x = ~factor(Specialization),
    y = ~tot_students,
    type = 'bar',
    text = ~tot_students,
    textposition = 'outside',
    marker = list(color = 'steelblue')
  ) %>% 
    layout(
      xaxis = list(title = "Specializations"),
      yaxis = list(
        title = "Students",
        tick0 = 0,
        dtick = 25
    )
    )
})
```

### Breakdown by Minor
```{r}
renderPlotly({
  
  plot_ly(
    data = plot2(),
    x = ~factor(Minor),
    y = ~tot_students,
    type = 'bar',
    text = ~tot_students,
    textposition = 'outside',
    marker = list(color = 'plum')
  ) %>% 
    layout(
      xaxis = list(title = "Minor"),
      yaxis = list(
        title = "Students")
    )
})
```

# Cohort Data


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
shinyWidgets::checkboxGroupButtons(
    inputId   = "checkbox_students",
    label     = h4("Cohort Report Students"),
    choices   = unique(cr$SCHEV_STUSTAT),
    selected  = unique(cr$SCHEV_STUSTAT),
    checkIcon = list(
        yes = icon("ok", lib = "glyphicon"),
        no  = icon("remove", lib = "glyphicon")
    ))

shinyWidgets::pickerInput(
    inputId  = "picker_startterm",
    label    = h4("Cohort Start Term"),
    choices  = unique(cr$START_TERM),
    selected = unique(cr$START_TERM),
    multiple = TRUE,
    options  = list(
        `actions-box` = TRUE,
        size = 10,
        `selected-text-format` = "count > 2"
    )
)

br()
hr()
br()

actionButton(inputId = "reset", label = "Reset", icon = icon("sync"))

observeEvent(eventExpr = input$reset, handlerExpr = {
    
    updatePickerInput(
        session = session,
        inputId = "checkbox_students",
        selected = unique(cr$SCHEV_STUSTAT))
  
      updatePickerInput(
        session = session,
        inputId = "picker_startterm",
        selected = unique(cr$START_TERM))
    
        
})

```


Row {data-width=650}
-----------------------------------------------------------------------
```{r}
summary3 <- reactive({
  
  cr %>%
    filter(SCHEV_STUSTAT %in% input$checkbox_students) %>% 
    filter(START_TERM %in% input$picker_startterm) %>% 
    
    summarise(
      
      cr_students = n_distinct(SCS_Student),
      grad_rates = mean(GRADUATED_OVERALL, na.rm = TRUE)
    ) %>% 
      
    mutate(
      
      grad_rates = scales::percent(grad_rates, 0.01)
      
    )
})
```


### A
```{r}
renderValueBox({
  
  valueBox(
    value = summary3()$cr_students,
    caption = "Total Students",
    color = "pink"
  )
  
})
```

### B
```{r}
renderValueBox({
  
  valueBox(
    value = summary3()$grad_rates,
    caption = "Graduation Rate",
    color = "lightyellow"
  )
  
})
```

Row {.tabset}
-----------------------------------------------------------------------

### Retention Rates

```{r}
summary4 <- reactive({
  
  cr %>% 
    filter(SCHEV_STUSTAT %in% input$checkbox_students) %>% 
    filter(START_TERM %in% input$picker_startterm) %>% 
  group_by(START_TERM) %>% 
  summarise(
    'Starting # of Students' = n(), 
    
    # Finding the average persistence for each semester
    persist2 = mean(ENROLLED_SEMESTER2, na.rm = TRUE),
    persist3 = mean(ENROLLED_SEMESTER3, na.rm = TRUE),
    persist4 = mean(ENROLLED_SEMESTER4, na.rm = TRUE),
    persist5 = mean(ENROLLED_SEMESTER5, na.rm = TRUE),
    persist6 = mean(ENROLLED_SEMESTER6, na.rm = TRUE),
    persist7 = mean(ENROLLED_SEMESTER7, na.rm = TRUE),
    persist8 = mean(ENROLLED_SEMESTER8, na.rm = TRUE)
  ) %>% 
  ungroup() %>% 
    mutate(
      persist2 = scales::percent(persist2, 0.01),
      persist3 = scales::percent(persist3, 0.01),
      persist4 = scales::percent(persist4, 0.01),
      persist5 = scales::percent(persist5, 0.01),
      persist6 = scales::percent(persist6, 0.01),
      persist7 = scales::percent(persist7, 0.01),
      persist8 = scales::percent(persist8, 0.01)) %>% 
    rename(
      `Fa to SpY1` = persist2,
      `Sp to FaY2` = persist3,
      `Fa to SpY2` = persist4,
      `Sp to FaY3` = persist5,
      `Fa to SpY3` = persist6,
      `Sp to FaY4` = persist7,
      `Fa to SpY4` = persist8
    )
  
})

DT::renderDataTable(expr = {
  
  summary4()
  
})
```

### Persistence Rates

```{r}
summary5 <- reactive({
  
  cr %>% 
    filter(SCHEV_STUSTAT %in% input$checkbox_students) %>% 
    filter(START_TERM %in% input$picker_startterm) %>% 
    group_by(START_TERM) %>% 
    summarise(
      'Starting # of Students' = n(), # Total number of students that started college in each year
    
      # Finding the average retention for each year
      Retained_Y2 = mean(RETAINED_YR2, na.rm = TRUE),
      Retained_Y3 = mean(RETAINED_YR3, na.rm = TRUE),
      Retained_Y4 = mean(RETAINED_YR4, na.rm = TRUE),
    ) %>% 
    ungroup() %>% 
    mutate(
      Retained_Y2 = scales::percent(Retained_Y2, 0.01),
      Retained_Y3 = scales::percent(Retained_Y3, 0.01),
      Retained_Y4 = scales::percent(Retained_Y4, 0.01))
  
})

DT::renderDataTable(expr = {
  
  summary5()
  
})
```



### Graduation Rates

```{r}
summary6 <- reactive({
  
  cr %>% 
    filter(SCHEV_STUSTAT %in% input$checkbox_students) %>% 
    filter(START_TERM %in% input$picker_startterm) %>% 
    group_by(START_TERM) %>% 
    summarise(
      'Starting # of Students' = n(), # Total number of students that started college in each year
    
      # Finding the average retention for each year
      grad_YR1 = mean(GRADUATED_1YR, na.rm = TRUE),
      grad_YR4 = mean(GRADUATED_4YR, na.rm = TRUE),
      grad_YR5 = mean(GRADUATED_5YR, na.rm = TRUE),
      grad_YR6 = mean(GRADUATED_6YR, na.rm = TRUE),
      overall_grad = mean(GRADUATED_OVERALL, na.rm = TRUE)
    ) %>% 
    ungroup() %>% 
    mutate(
      grad_YR1 = scales::percent(grad_YR1, 0.01),
      grad_YR4= scales::percent(grad_YR4, 0.01),
      grad_YR5 = scales::percent(grad_YR5, 0.01),
      grad_YR6 = scales::percent(grad_YR6, 0.01),
      overall_grad = scales::percent(overall_grad, 0.01))
  
})

DT::renderDataTable(expr = {
  
  summary6()
  
})
```


### Start Major vs. Grad Degree

```{r}

summary7 <- reactive({
  
  joined_data %>% 
    filter(SCHEV_STUSTAT %in% input$checkbox_students) %>% 
    select(`Student ID`, MAJOR_FIRST_TERM, SPECIALIZATION_FIRST_TERM, DEGREE, DEGREE_MAJOR) %>% 
    group_by(`Student ID`) %>% 
    ungroup()
  
  
})  
  
DT::renderDataTable(expr = {
  
  summary7()
  
})

```









